### ISSUE TITLE
Пропадание текстур с помощью дома

### ISSUE THREAD

**Issue by Tarfalgar** [salwador/MTA-Project-Zero#13]
суть такова,если ты заходишь в какой-то дом с помощью ключей или монтировки,в моем случаи это была амунация в лс,зашел туда без каких либо приспособлений,и там нажал ф7,когда улетел из амунации,считало что я все еще в ней,и не мог из-за этого что либо ставить,по типу мин и палаток,и пока ты не умрешь так и будет считаться и при заходе будут текстуры пропадать.

**Comment by R4tn1k** [comment]
надо просто туда обратно зайти и выйти и все будет норм

**Comment by salwador** [comment]
Исправлено. Будет загружено на сервера сегодня-завтра.
