### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Poroshok3** [salwador/MTA-Project-Zero#15]
Как исправить баг с невидимым лутом в руках и тд. Например: Рюкзак у мен на спине одет но его не видно, шлем одет но его не видно!

**Comment by salwador** [comment]
После чего это появляется?

**Comment by Poroshok3** [comment]
Оно и не пропадает, как случилось при втором заходе на сервер, так и есть до сих пор

**Comment by salwador** [comment]
@Poroshok3, откатите МТА https://nightly.mtasa.com/mtasa-1.5.5-full_rc-11999-20180604.exe
