### ISSUE TITLE
Помогите.

### ISSUE THREAD

**Issue by twenty1ne** [salwador/MTA-Project-Zero#17]
засунул сундук под текстуру, и еще другие после снесения он остался, иконки для взорвать ну и обыскать нету, как только не вводил мышкой, в нашей стране Кыргызстан в прошлом году ввели закон об том чтобы запретить переводы типо киви кошелек вебмани яндекс и тд, карточки нет, несовершеннолетний, прошу снести.
https://imgur.com/a/dIa1AtK

**Comment by twenty1ne** [comment]
Мой ник если что [Святые] Малой :З

**Comment by bengol12** [comment]
Здравствуйте меня забанили по ошибке я играю 3 день даже не умел толком играть поставил палатку положил лут и меня кикает консоль и я в бане администрация пожалуйста розберитесь с проблемой и ещё у меня бан на 5лет
