### ISSUE TITLE
баг на невидимость

### ISSUE THREAD

**Issue by R4tn1k** [salwador/MTA-Project-Zero#18]
**Описание бага.**
баг с хаммером, при помощи которого становишься невидимым

**Воспроизведение.**

1. 1-ый игрок Подходит к хаммеру
2. Закрепляется
3. 2-ой игрок садится за руль и утопляет хаммер, а тот кто на закрепе ничегоомента когда хаммер зареспавнится

**Последствия.**
тот кто стал невидимым может кидать гранаты и резать с ножа

**Подтверждение**
По возможности, прикрепите скриншоты или видео.

**Дополнительная информация**
Сменить текстуру хаммера или самого хаммера чтобы нельзя было закрепиться

**Обратная связь**
Ratnik  https://vk.com/id232127345

**Comment by R4tn1k** [comment]
> **Описание бага.**
> баг с хаммером, при помощи которого становишься невидимым
> 
> **Воспроизведение.**
> 
> 1. 1-ый игрок Подходит к хаммеру
> 2. Закрепляется
> 3. 2-ой игрок садится за руль и утопляет хаммер, а тот кто на закрепе ничего до момента когда хаммер зареспавнится
> 
> **Последствия.**
> тот кто стал невидимым может кидать гранаты и резать с ножа
> 
> **Подтверждение**
> По возможности, прикрепите скриншоты или видео.
> 
> **Дополнительная информация**
> Сменить текстуру хаммера или самого хаммера чтобы нельзя было закрепиться
> 
> **Обратная связь**
> Ratnik https://vk.com/id232127345

**Comment by salwador** [comment]
Исправлено. Будет загружено на сервера сегодня-завтра.
Огромное спасибо, отпишите пожалуйста в сообщения сообщества по поводу вознаграждения.
