### ISSUE TITLE
Баг на невидимость.

### ISSUE THREAD

**Issue by Westmen** [salwador/MTA-Project-Zero#19]
Баг, с помощью которого ты становишься невидимым, и можно таким образом зайти в базу и вынести от туда все..
1. Необходим вертолет и санчез.
2. Садимся в санчез, затем загоняем его в грузовой отсек вертолета.
3. Слазим с санчеза и прямо в вертолёте нажимает закрепиться, после закрепа в вертолете, садимся на санчез, отъезжаем от вертолете и становимся невидимым для всех.
4. Итог - вы невидимы и ваше тело остается в вертолете, по желанию необходим второй человек, который будет охранять вас. При всём этом когда невидимый человек подбирает лут, то при выбрасывании он падает именно в вертолет.
К сожалению снять видео нет возможности, так как на поиск вертолета и санчеза уйдет большое кол-во времени, при необходимости могу все показать, если администрация предоставит все для этого.
Ссылка на вк https://vk.com/eduard199686

**Comment by salwador** [comment]
Исправлено. Будет загружено на сервера сегодня-завтра.
Огромное спасибо, отпишите пожалуйста в сообщения сообщества по поводу вознаграждения.
