### ISSUE TITLE
bug: Chevrolet C10

### ISSUE THREAD

**Issue by Eweest** [salwador/MTA-Project-Zero#2]

**Comment by motenad** [comment]
Баг с зомби. Например дерёшься с ним на дороге под углом, или на горе, то они начинают телепортироваться то за спину, то опять перед тобой. В итоге кусают тебя даже без анимации. Ещё баг с разными коробками и палетами. Об них можно споткнуться без причины. Даже когда ты рядом стоишь. И это наносит урон.  Ещё для постройки гвозди очень трудно найти.  Если вы решили изменить правила постройки что нужен фундамент. Значит материалов нужно больше. Фундамент, 3 стены, крыша, дверная арка и само собой дверь для минимальной постройки. Это более ресурсозатратно касательно гвоздей.  Может чуть чуть повысить генерацию гвоздей вместе с этим обновлением? Ещё проблемы со снайперской винтовкой. У неё почти нет урона. Вчера с другом воевали против ботов. Со снайперки мы не одного не убили. А вот с пистолета с беретты практически в пару выстрелов попали.
