### ISSUE TITLE
Баг с разжиганием печки/костра.

### ISSUE THREAD

**Issue by eugene27r** [salwador/MTA-Project-Zero#25]
Невозможность разжечь печку/костёр при наличии спичек в инвентаре.

1. Спички в инвентаре, костёр/печка разложены на земле.
2. Выбрать пункт "разжечь" в меню.
3. Ничего не происходит.

![image](https://user-images.githubusercontent.com/52146881/60059381-b8ba8780-972f-11e9-8336-ab67610ff3e2.png)

Спички "рабочие" в других ситуациях. Например: сигареты.

**Comment by salwador** [comment]
Вроде поправил
