### ISSUE TITLE
Содержимое канистры не может быть вылито на землю.

### ISSUE THREAD

**Issue by eugene27r** [salwador/MTA-Project-Zero#26]
Содержимое канистры не выливается на землю.

1. Канистра в инвентаре.
2. После выбора пункта "вылить на землю" ничего не проиходит.

![image](https://user-images.githubusercontent.com/52146881/60059545-41392800-9730-11e9-831f-e899c1fd9538.png)

Содержимое остальных ёмкостей (фляжка, бутылка и т.д.) выливается.

**Comment by salwador** [comment]
Вроде поправил
