### ISSUE TITLE
Дюп сишек.

### ISSUE THREAD

**Issue by Algololik** [salwador/MTA-Project-Zero#29]
**Описание бага.**
С помощью этого бага у меня дюпались сишки, хотя у меня было ингредиентов только на одну, я не стал употреблять этим и создал только три.
**Воспроизведение.**
1. Берем ингредиенты для с4.
2. Заходим в меню крафта и делаем сишки, при этом ингредиенты не кончаются.

**Последствия.**
Бесконечное с4

**Подтверждение**
![mta-screen_2019-06-24_23-08-49](https://user-images.githubusercontent.com/52219287/60131054-8483ad00-97a9-11e9-87f9-36707c879f60.png)
![mta-screen_2019-06-24_23-08-51](https://user-images.githubusercontent.com/52219287/60131055-851c4380-97a9-11e9-8781-8ec85ece1df0.png)
![mta-screen_2019-06-24_23-08-52](https://user-images.githubusercontent.com/52219287/60131056-851c4380-97a9-11e9-9482-232ffaaa7752.png)
![mta-screen_2019-06-24_23-08-59](https://user-images.githubusercontent.com/52219287/60131060-851c4380-97a9-11e9-8f2e-42eb163030a5.png)
![mta-screen_2019-06-24_23-09-05](https://user-images.githubusercontent.com/52219287/60131064-85b4da00-97a9-11e9-89e5-b83f20cc5a1f.png)
![mta-screen_2019-06-24_23-09-10](https://user-images.githubusercontent.com/52219287/60131066-864d7080-97a9-11e9-8b84-abd2ea17ddf3.png)
![mta-screen_2019-06-24_23-09-21](https://user-images.githubusercontent.com/52219287/60131074-8b122480-97a9-11e9-9fb7-ace2eb0f69f3.png)

**Дополнительная информация**
Исправить данный дюп, раньше его не наблюдалось.

**Обратная связь.
Сервер №2, Ник: Степаша.
Вк: Сервер № 2, ник: Степаша.
ВК: https://vk.com/black.berry0

**Comment by bibka2000** [comment]
Кстати что-то с менюшкой крафта тип решил я создать шину нарвал кликаю кликаю а оно отображает что ресурсы еще есть.

**Comment by Algololik** [comment]
> Кстати что-то с менюшкой крафта тип решил я создать шину нарвал кликаю кликаю а оно отображает что ресурсы еще есть.

Ну видимо и с шиной также ;)

**Comment by salwador** [comment]
@Algololik, то что не обновляется меню после крафта - знаем, конечно будет исправлено. Но это никак не связано и не даёт возможности крафтить без ресурсов. Ни я, ни другой модератор не смогли подтвердить наличие этого бага. :thinking: 

Может что-то ещё? По логам вы "скрафтили" 3 взрывчатки, одна из которых была позже.

22:07:48 | *** | Скрафтил x1 bomb
22:07:49 | *** | Скрафтил x1 bomb
22:08:47 | *** | Скрафтил x1 bomb

**Comment by Algololik** [comment]
> @Algololik, то что не обновляется меню после крафта - знаем, конечно будет исправлено. Но это никак не связано и не даёт возможности крафтить без ресурсов. Ни я, ни другой модератор не смогли подтвердить наличие этого бага. 🤔
> 
> Может что-то ещё? По логам вы "скрафтили" 3 взрывчатки, одна из которых была позже.
> 
> 22:07:48 | *** | Скрафтил x1 bomb
> 22:07:49 | *** | Скрафтил x1 bomb
> 22:08:47 | *** | Скрафтил x1 bomb

Значит мне показалось

**Comment by salwador** [comment]
Нет подтверждения
