### ISSUE TITLE
Bug:stair

### ISSUE THREAD

**Issue by DeDuIIIkA** [salwador/MTA-Project-Zero#3]
На промзоне возле казарм есть лестница ведующая на крышу здания, иногда за метр от этой лестницы, срабатывает анимация забирания по этой лестнице и в итоге ломаешь ноги из-за этого

**Comment by salwador** [comment]
Не особо понял, да и где лестница - не в курсе. О таком лучше сообщать со скринами или видео.

**Comment by DeDuIIIkA** [comment]
возле казарм на пром зоне,у крайней казармы есть лестница ведущая на крышу красного здания,что рядом с этими казармами
