### ISSUE TITLE
Баг с  крафтом

### ISSUE THREAD

**Issue by OberBlock** [salwador/MTA-Project-Zero#30]
**Описание бага.**
Если войти в меня крафта , то при нажатии на крафт любого предмета ресурсы остаются и так же появляется и предмет который мы скрафтили.

**Воспроизведение.**

1. Открыть меню крафта 
2. Нажать на любой предмет
3. Ископаемое остается ( ресурс ) 
4. К тому же добавляется в инвентарь предмет на который нажали
5. Итог бага: Бесконечный дюп предметов из меню крафта
P.S: Если войти в меня крафта , то при нажатии на крафт любого предмета ресурсы остаются и так же появляется и предмет который мы скрафтили.

**Последствия.**
Бесконечный дюп предметов из меню крафта.

**Дополнительная информация**
Это проверяется не с первого раза"!!!"
Для того , что б это получилось нужно:
Быстро нажимаем на кнопку крафта определённого предмета ( уже в меню крафта)

**Обратная связь**
1 сервер.   НИК:  ДедШот
2 сервер.   НИК:  ДедШот 
ВК:    https://vk.com/danil_emelyanov99
Discord/Дискорд:   Ober_Block#4600

**Comment by salwador** [comment]
Если есть возможность - запишите видео. Хоть в 20 FPS, потому что были ресурсы на 10 предметов, так их 10 и скрафтилось, и ни одним больше. :man_shrugging:

**Comment by OberBlock** [comment]
> Если есть возможность - запишите видео. Хоть в 20 FPS, потому что были ресурсы на 10 предметов, так их 10 и скрафтилось, и ни одним больше.

Здравствуй Сальвадор, Хорошо я запишу видео , просто причина в том , что ресурсы багються, и вам нужно иметь определённое кол-во ресурсов для предмета , в случаи если у вас ресурсов на 1 предмет , то скрафтить 1 предмет, но ресурсы остаются, если передать эти ресурсы другому игроку он сделает тоже самое , и получается , что можно сделать покругу и ресурсы на 1 предмет останутся , а скрафченный предмет будет появлять и появляться

**Comment by Algololik** [comment]
> > Если есть возможность - запишите видео. Хоть в 20 FPS, потому что были ресурсы на 10 предметов, так их 10 и скрафтилось, и ни одним больше.
> 
> Здравствуй Сальвадор, Хорошо я запишу видео , просто причина в том , что ресурсы багються, и вам нужно иметь определённое кол-во ресурсов для предмета , в случаи если у вас ресурсов на 1 предмет , то скрафтить 1 предмет, но ресурсы остаются, если передать эти ресурсы другому игроку он сделает тоже самое , и получается , что можно сделать покругу и ресурсы на 1 предмет останутся , а скрафченный предмет будет появлять и появляться

Нет, этого не может быть, у тебя ресурсы исчезают. Это меню крафта багнутое и уже есть несколько тем на данный баг.

**Comment by salwador** [comment]
Нет подтверждения

**Comment by OberBlock** [comment]
Сальвадор срочно!!!!
Я нашёл ДЮП ваш простите ёбанный человек который сидит в тех поддержке группы не мог мне сказать просто информацию , которую я не знал , по поводу вознагрождения!
И при этом кинул меня в чс!!! Мне с вами в вк надо поговорить сюда трекер кидать я не буду , так как можно будет пользоваться всей этой шнягой... просто прочитав информацию!!!

**Comment by OberBlock** [comment]
> Нет подтверждения

Я скину подтверждение вам только в вк и расскажу  про дюп! Это очень важно!!!
Видео так же в вк , и просто я бы хотел узнать по поводу вознаграждения, ах да и ещё разве приличный сервер стал бы посылать нахуй подписчика и игрока... 
![image](https://user-images.githubusercontent.com/52260331/60397346-d2efcd80-9b54-11e9-9181-7e1e49843b26.png)

**Comment by OberBlock** [comment]
И к тому же не в рублях  , а игровой валюты!!!

**Comment by salwador** [comment]
@OberBlock когда вам не ответили про вознаграждение - вы удосужились удалить сообщение с и без того кривым пояснением бага. Повторю - с таким отношением можете засунуть этот баг себе в жопу.

То что вы клянчите валюту как бомжи у церкви - не делает вас "ценным". Исходя из того что то что  вы прислали - не работает, делаем выводы о том - что вы даже не в состоянии нормально описать баг.

**Comment by OberBlock** [comment]
Во-первых я не клянчу, а просто спросил!
Во-вторых я могу скинуть вам в группу видео, но я в  чс.. 
В-третьих это не баг , а дюп
В-четвёртых для чего был этот шантаж, Я сказал, что я знаю один об этом дюпе , а вы сказали, что вы знаете кто его знает,  и очень не хотелось, что б меня забанили, не чего не говорит о намёках, шантаж... а если вы так не думаете , то закон читать надо

**Comment by OberBlock** [comment]
Если вам так нужно видео, я буду общаться как ва со мной , то я блять вам его скину. раз вы имеете право меня посылать то и я , щас не хуя мне не дадите , а я просто сделаю сервер лучше!... понимаете , я не собираюсь с сервера уходить, просто я долго его искал играю около 3 лет)) и не хочу с вами иметь какие-то плохие  отношения, в КОММЕНТЫ ПРЯМ СЮДА СКИНЕТ ВИДЕО ТОВАРИЩ!!!!

**Comment by OberBlock** [comment]
С дюпом к тому же можно дюпать вещи от 1 ДО 8!!!

**Comment by OberBlock** [comment]
@salwador
