### ISSUE TITLE
Текстурные места для палаток . 

### ISSUE THREAD

**Issue by howa15** [salwador/MTA-Project-Zero#33]
Текстурные нычки . 

**Воспроизведение.**
Все в видео .  https://vk.com/video183909516_456239322?list=2ba3a651f2bf8a6f21 
https://vk.com/video183909516_456239323?list=8f0d508b1b6a2ddaea
https://vk.com/video183909516_456239324?list=abd439242b36f11c47 
Вк : https://vk.com/id183909516

**Comment by howa15** [comment]
> Текстурные нычки .
> 
> **Воспроизведение.**
> Все в видео . https://vk.com/video183909516_456239322?list=2ba3a651f2bf8a6f21
> https://vk.com/video183909516_456239323?list=8f0d508b1b6a2ddaea
> https://vk.com/video183909516_456239324?list=abd439242b36f11c47

Вк https://vk.com/id183909516

**Comment by eugene27r** [comment]
Невозможно просмотреть видео.
![image](https://user-images.githubusercontent.com/52146881/60483104-723cce00-9cd7-11e9-8773-e038a60e5e5d.png)
