### ISSUE TITLE
Дюп любого оружия и все что на нем (обвесы,патроны)

### ISSUE THREAD

**Issue by AkihabaraAkihiko** [salwador/MTA-Project-Zero#34]
Дюп оружия и всех обвесов и патрон в нем.
Воспроизведение.
1. Открываем инвентарь.
2. Затем перетаскиваем на 1 слот (то что хотим дюпнуть), на 2 (то что хотим отдать в преисподню). 
3. Затем берем в руки оружие (которое хотите дюпунть), вытаскиваем LAN-кабель и быстро нажимаем 1-2. После вставляем LAN-кабель.
4. Вуаля, у вас заменяется предмет на 2 слоте (не всегда так, может заменить наоборот) и появляется дюпнутое оружие от 1 замены до 10 за раз получится может.

**Последствия.**
Бесконечные патроны,оружие,обвесы (может с4 тоже можно дюпнунть, не пробовал)
Так же можно дюпать гранаты и т.п
**Подтверждение**
https://www.youtube.com/watch?v=ByNaXu_L6Rg

**Дополнительная информация**
Исправить легко + добавит лучшего геймплея в игре. И так, исправить это можно... Если поставить задержку на доставание оружия в быстром слоте (например 5-10сек)

**Обратная связь**
Баг нашли мы с другом, и прошу разделить вознаграждение (если он будет) напополам.
Я https://vk.com/gooooook  Серийник мой и моего друга (при вознаграждении) я скину в вк

**Comment by salwador** [comment]
Поздно спохватились, уже не актуально.

**Comment by AkihabaraAkihiko** [comment]
Всм?
