### ISSUE TITLE
баг с торговцем

### ISSUE THREAD

**Issue by aligator35** [salwador/MTA-Project-Zero#36]
**Описание бага.**
фарм ржавых листов

**Воспроизведение.**
Удалите это, и напишите что надо предпринять для его воспроизведения.
1. обменятся с торговцем
2. Сделать что-то
3. Прыгнуть куда-то
4. Увидеть последствия бага

**Последствия.**
Удалите это, и напишите что происходит в деталях, и как это влияет на игру?

**Подтверждение**
![mta-screen_2019-07-02_18-56-50](https://user-images.githubusercontent.com/52121519/60522068-c492e480-9d01-11e9-9532-bb1ee6226a39.png)
![mta-screen_2019-07-02_18-56-51](https://user-images.githubusercontent.com/52121519/60522069-c52b7b00-9d01-11e9-97ad-fb9a71a53c75.png)
![mta-screen_2019-07-02_18-56-11](https://user-images.githubusercontent.com/52121519/60522071-c52b7b00-9d01-11e9-9aba-1fa6dc223d43.png)

**Дополнительная информация**
Добавьте сюда что-то ещё, если считаете что это поможет нам в обнаружении и исправлении.

**Обратная связь**
kotik

**Comment by salwador** [comment]
Где нормальное описание? В чём заключается баг? Почему весь репорт со стандартным текстом?

**Comment by eugene27r** [comment]
Создан новый репорт с этим багом.
