### ISSUE TITLE
При обмене с торговцами расходуются не все вещи.

### ISSUE THREAD

**Issue by eugene27r** [salwador/MTA-Project-Zero#37]
**При обмене с торговцами расходуются не все вещи.**

> Пример:
> 1. Взять нужные компоненты для обмена. 
> Например, мы производим обмен на лист ржавого металла. Нужно взять: лист металла, GPS, часы.
> 2. Выполнить обмен.
> 3. Лист ржавого металла в нашем инвентаре. Из наших компонентов потратился только GPS.

Пробежавшись по торговцам, можно составить такой список.
При обмене на _ не расходуются _ :
*на **HK416** не расходуется **Glock 17**.
*на **Очки теплового видения** не расходуются **Молоток** и **GPS**.
*на **Активированный уголь** не расходуется **Яблоко**.
*на **Акваланг** не расходуется **Рюкзак Hazer**.
*на **M1911** не расходуется **Осколочная граната**.
*на **Beretta M9** не расходуется **Осколочная граната**.
*на **Жаренное мясо** не расходуются **Бутылка воды** и **Помидор**.
*на **Армейский камуфляжный рюкзак** не расходуются **Самодельный рюкзак** и **Фонарик**.
*на **Вакцина** не расходуются **Гвозди**.
*на **Лист ржавого металла** не расходуются **Лист металла** и **Часы**.
*на **Пила** не расходуется **Молоток**.
*на **Ключи от дома** не расходуется **Пачка сигарет**.
*на **GPS** не расходуются **Спички** и **Карта**.
*на **АК5С** не расходуется **М1911**.
*на **Топор** не расходуется **Кирка**.

**Comment by salwador** [comment]
Исправлено. Будет загружено со следующим патчем.
