### ISSUE TITLE
Точка строительства

### ISSUE THREAD

**Issue by ElektroKILLER** [salwador/MTA-Project-Zero#40]
**Описание бага.**
Например если поставить пару фундаментов в притык концу точки,то расстояние или высота строительства других частей будет разная,типо ты ставишь стену на одном фундаменте а на другом так же ты не сможешь поставить так как не будет продвигаться дальше или выше и тд в режиме строительства 

**Обратная связь**
https://vk.com/artaaae

**Comment by salwador** [comment]
Это не баг. Расстояние рассчитывается от центра точки до новой позиции объекта. Здесь нет ошибки,  потому что в проекции это будет сферой. Чем ближе к краю - тем меньше доступная высота.
![image](https://user-images.githubusercontent.com/12719219/61183070-a4f3a880-a67f-11e9-8020-87d4453fc89f.png)
