### ISSUE TITLE
Body is invisible.

### ISSUE THREAD

**Issue by Huba013** [salwador/MTA-Project-Zero#51]
**What happen.**
In place you body is invisible and can see only backpack, helmet and armor. And can see this glitch behind door car/small helicopter when u stay you body is invisible

**How do it?**
**1**.Found car/small heli and open door, next go under open door and stay, next take camera before door and u see only backpack, helmet and armor
**2**.And in other place body is glitched and invisible (zone48)

**Photo**
![mta-screen_2019-12-07_17-57-40](https://user-images.githubusercontent.com/58894543/70926220-0522b800-202d-11ea-8df0-bd7f8c3bd3bc.png)

**Concat**
Discord: #8955Huba013

**Found**Huba013

**Comment by salwador** [comment]
GTA/MTA Bug
