### ISSUE TITLE
Бесконечная линия у обучения

### ISSUE THREAD

**Issue by LifaRaf** [salwador/MTA-Project-Zero#54]
Думаю не нужно описание
Здоровье тратиться, но долго
**discord для связи LifaRaf#5759
![mta-screen_2019-12-27_23-39-18](https://user-images.githubusercontent.com/59294956/71532404-f8e40800-2914-11ea-8ecd-13ce6ace34a3.png) 
![mta-screen_2019-12-27_23-41-28](https://user-images.githubusercontent.com/59294956/71532405-f8e40800-2914-11ea-8cbb-14e3c4b15c11.png)

**Comment by salwador** [comment]
Fixed in next build
