### ISSUE TITLE
[BUG] Construction

### ISSUE THREAD

**Issue by Nonamelll** [salwador/MTA-Project-Zero#7]

**Comment by Nonamelll** [comment]
??????

![mta-screen_2017-12-18_19-28-35](https://user-images.githubusercontent.com/34661672/34129095-03e2d36c-e42a-11e7-8191-9de41d8ade0b.png)
![mta-screen_2017-12-18_19-29-33](https://user-images.githubusercontent.com/34661672/34129096-041ab34a-e42a-11e7-8584-010806eefcb1.png)

**Comment by salwador** [comment]
No description
