### ISSUE TITLE
Ошибка сервера : *** NETWORK TROUBLE ***

### ISSUE THREAD

**Issue by RiKoTTo** [salwador/MTA-Project-Zero#9]
![1](https://user-images.githubusercontent.com/36801977/36635276-1792d898-19c3-11e8-864f-16126c2c73b0.png)
![2](https://user-images.githubusercontent.com/36801977/36635277-17baacf6-19c3-11e8-882d-0d69431e3d13.png)
![3](https://user-images.githubusercontent.com/36801977/36635279-17e14cb2-19c3-11e8-97a2-3fcd03ca61ec.png)
![4](https://user-images.githubusercontent.com/36801977/36635280-180898c6-19c3-11e8-8818-20bb6805d5a2.png)
![5](https://user-images.githubusercontent.com/36801977/36635281-1831aaf4-19c3-11e8-8cab-4ad2a7fd33d5.png)

Доброго Времени Суток . Ошибка заключается вот в чем : допустим , ты играешь , и , либо релут уже был , либо ещё нет , и вдруг начинает выходить эта вот ошибка по середине экрана красными заглавными буквами : *** NETWORK TROUBLE *** , при том постоянно , в интервале примерно в 2-3 минуты наверно , и это у всех игроков на сервере ,выходит эта вот запись и персонаж зависает на месте . А бывает ещё вот так : когда происходит релут на сервере , то велика вероятность того , что на экран снова может выйти эта ошибка , но только в этот раз уже игра не просто зависает а просто вылетает , точнее говоря САМ СЕРВЕР ПАДАЕТ , т.е. все вылетают в этот момент из сервера .

P.S.  Данная ошибка очень раздражает , бесит , комфортность на сервере падает , и удовольствие от игры так же . Я очень надеюсь , что я не зря тут писал весь этот текст и что Администрация этого замечательного проекта примет соответствующие меры :) С Уважением , Ваш Игрок ;P

**Comment by salwador** [comment]
Падает сервер, это когда он сам по себе отключается - и вы не можете на него зайти.

А учитывая что ранее всё работало нормально, а иногда (пару раз в месяц) всё же происходит такая херня, то свожусь к тому - что хостинг подтупливает местами.

**Comment by RiKoTTo** [comment]
Теперь ясно , теперь я знаю , что значит "сервер падает" . Раньше как раз-таки все работало просто замечательно , эта ошибка , по моему мнению , появилась после последнего обновления (так как раньше реально такого не было) , видимо что-то не то затронули или чего-то не учли при обновлении...Если хостинг подтупливает местами - то почему же он не подтупливал раньше ?

**Comment by salwador** [comment]
Могу гарантированно сказать то, что последние изменения никак не могли повлиять на работоспособность сервера. А с хостингом бывает, почему нет то.
